name: squashy
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_storage: ^12.4.4
  firebase_ui_auth: ^1.16.1
  firebase_ui_oauth_google: ^1.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/squash.png
